language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
- stable
sudo: false
script:
- npm install
- npm test
deploy:
  provider: npm
  email: manager@mathjax.org
  api_key:
    secure: VyQLfUM+kLK4qNVdu6eqGO5Z5/raIuPL/fvnDvbf0KR4asHb3ieb9Q6YrHCMSKWGrVDx7sMn5xnk2TmcxL+9z3C1+wZIB+pBFTkcIZLMj+l/bwukJ0onTdfnOZPFxnBukgkgiXLpEzEIwJ6R+ULq0UsFhYni1eS9bp7hRn1+7Q4=
  on:
    tags: true
